### ISSUE TITLE
using blade in wpemerge-theme

### ISSUE THREAD

**Issue by 9585999** [htmlburger/wpemerge-theme#10]
Hi, how use this theme with wpmerge-blade?

Is it normal that standard templates are not defined if they are not explicitly indicated in routs behavior?

**Comment by atanas-dev** [comment]
Hi @9585999 ,

> Hi, how use this theme with wpmerge-blade?

Follow the Quickstart directions here: https://github.com/htmlburger/wpemerge-blade
The steps are the same - your providers array is in `app/config.php`.

> Is it normal that standard templates are not defined if they are not explicitly indicated in routs behavior?

Not exactly sure what you mean - could you please clarify?

**Comment by 9585999** [comment]
@atanas-angelov-dev 

> Follow the Quickstart directions here: https://github.com/htmlburger/wpemerge-blade
The steps are the same - your providers array is in app/config.php.

I followed these steps ...

`composer require htmlburger/wpemerge-blade`

```php
// config.php

'providers'         => [
    \App\Routing\RouteConditionsServiceProvider::class,
    \WPEmergeBlade\View\ServiceProvider::class,
],
```

```php
// functions.php

$container = WPEmerge::getContainer();
$container[ WPEMERGE_VIEW_ENGINE_KEY ] = function ($container) {
    return new \WPEmerge\View\NameProxyViewEngine([
        '.blade.php' => WPEMERGEBLADE_VIEW_BLADE_VIEW_ENGINE_KEY,
    ], WPEMERGEBLADE_VIEW_BLADE_VIEW_ENGINE_KEY);
};
```

>Not exactly sure what you mean - could you please clarify?

for example I have a template `front-page.blade.php`, which should be displayed on the page, which is set in the settings to the front. Or even an easier example: any page that does not exist should give the `404.blade.php` template by default, but it does not happen until in the routs explicitly specified ...

```php
Router::get(['post_id', get_option('page_on_front')], function ($request, $view) {
    return app_view('front-page');
});

Router::get('*', function ($request, $view) {
    return app_view('404');
});
```

If the paths are not explicitly specified in the routes, the blade patterns do not work, it works out index.php ...

**Comment by atanas-dev** [comment]
Don't add that snippet to functions.php - this is an example snippet from the docs for when you need mixed view engines. Adding the provider is enough for blade-only.

> but it does not happen until in the routs explicitly specified

The core WordPress template names remain the same without the `.blade.php` extension (i.e. only `.php`). If Blade is your view engine it will still render them as blade even through the extension is not `.blade.php`.
- 404 = `404.php`
- front page = `front-page.php`
- any custom template = can be both `templates/custom.php` and `templates/custom.blade.php` - the Blade view engine for WP Emerge will find it either way.

I'll probably end up adding a filter for core templates so they resolve to `.blade.php`, if they exist, to avoid confusion.

**Comment by 9585999** [comment]
@atanas-angelov-dev 

Thank you for clarifying the situation.

I just used Sage, so there all the files .blade.php, that's why I decided that something is wrong here :)

**Comment by atanas-dev** [comment]
No worries - I see why it can be confusing. Thanks for bringing it up - I'll make sure this improvement makes it into the next version :)
