### ISSUE TITLE
Sprite with SVG icons?

### ISSUE THREAD

**Issue by kristjankoppel** [htmlburger/wpemerge-theme#11]
Is it correct that at the moment developers can't make sprite out of svg files? I looked at config files and so that something like spritesmith is used. I also searched for spritesmith documentation and didn't find anything about svg's. 

So if it is correct then i propose for a feature request here :) Maybe something that can deal with svg files and make sprite out of them. OR something that would generate data:uri code.

**Comment by atanas-dev** [comment]
Hi @kristjankoppel ,

Yes, spritesmith does not support svg - if focuses on raster images instead.
Marking this as a feature request.

**Comment by kristjankoppel** [comment]
If you can put a milestone to this feature then it would be awesome. With Gulp i used  https://github.com/jkphl/gulp-svg-sprite 

At the moment i'll then keep svg's in a seperate files or convert them to data:uri.

**Comment by atanas-dev** [comment]
An SVG sprite has been added in [0.16.0](https://github.com/htmlburger/wpemerge/releases/tag/0.16.0) 👍
