### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by 9585999** [htmlburger/wpemerge-theme#12]
Hi, how i can upload localization files for this repo?...

**Comment by atanas-dev** [comment]
Hi @9585999 ,

Localization files are found under in the `languages/` directory (https://github.com/htmlburger/wpemerge-theme/tree/master/languages).
If you'd like to contribute a translation, feel free to create one from the app.pot file and submit a PR with the new .po and .mo files (make sure you start from the latest `master`).

**Comment by 9585999** [comment]
@atanas-angelov-dev 

the fact is that I want to contribute to the development of this project, when I try to upload files to the repository, I get such a message ...

![img 2018-09-06 13 41 06](https://user-images.githubusercontent.com/16165904/45152799-b99f1e80-b1da-11e8-8e2b-bb32b45f5e6a.PNG)

**Comment by atanas-dev** [comment]
You must create a fork repository and submit a PR from that fork - not upload directly.

**Comment by 9585999** [comment]
@atanas-angelov-dev ок, I will do :)
