### ISSUE TITLE
include JS Framework

### ISSUE THREAD

**Issue by 9585999** [htmlburger/wpemerge-theme#14]
I'm not very strong in webpack settings, since there are also pressets in the laravel, so can you tell me how to properly integrate Vue js into this topic? :)

**Comment by atanas-dev** [comment]
React and Vue as options during install are under consideration so there's no ETA.

As for doing it manually, you should be able to use it just by requiring Vue. If you want single file `.vue` component support check out the docs here:
https://vue-loader.vuejs.org/guide/#vue-cli

**Comment by 9585999** [comment]
@atanas-angelov-dev ok thanks.
