### ISSUE TITLE
Error while installing "The command "yarn add "'popper.js'@^1.14"" failed."

### ISSUE THREAD

**Issue by kristjankoppel** [htmlburger/wpemerge-theme#16]
Hi!

Since today - when i try to install project with Bootstrap i get error like this: https://jmp.sh/0oxy2cu

Yesterday all worked fine. Maybe this is something with new release?

**Comment by atanas-dev** [comment]
Hi @kristjankoppel ,

Please run `composer update` until it downloads `htmlburger/wpemerge-cli` version `0.11.1` - this hotfix should resolve the issue.

**Comment by kristjankoppel** [comment]
Ok `wpemerge-cli` updates to 0.11.1 but how i trigger installation again? It quits and don't add needed files. Even if i do yarn install manually it installs only dependencies from package.json file. Missing Bootstrap and any other option i selected in create-project step.

**Comment by atanas-dev** [comment]
You will have to manually clean up after the failed CLI install unfortunately - should be something like this:
1. `yarn remove bootstrap popper.js` - this may fail as some of the packages may not be installed anyway.
2. `rm resources/scripts/theme/vendor/bootstrap.js` - make sure to keep a backup of this file if you have made any changes to it.
3. `./vendor/bin/wpemerge install` to reinstall your desired package.
