### ISSUE TITLE
404 Not Found: 'tailwindcss'@^0.6.5

### ISSUE THREAD

**Issue by ProxyAi** [htmlburger/wpemerge-theme#17]
## Version

  - WP Emerge Starter Theme: 0.11.0
  - WP Emerge (if not the default):
  - WordPress: N/A
$ nodejs -v
v11.2.0

$ npm -v
6.4.1

$ php -v
PHP 7.2.11-2+0~20181015120510.9+jessie~1.gbp8105e0 (cli) (built: Oct 16 2018 03:39:58) ( NTS )

## Comments

On install on these using the quick start guild im guessing the following error on the composer step

![image](https://user-images.githubusercontent.com/11992984/48626443-c3e35300-e9a9-11e8-87f2-9652c4eec3d9.png)

**Comment by atanas-dev** [comment]
Hi @xorenio ,

Could you please confirm you are on the latest wpemerge-cli version? Run this in your theme directory:
`./vendor/bin/wpemerge --version`

**Comment by ProxyAi** [comment]
$ ./vendor/bin/wpemerge --version
WPEmerge CLI 0.11.0

**Comment by atanas-dev** [comment]
~I can't reproduce the issue - can you try running this and let me know if it fails:
`npm install tailwindcss@^0.6.5`~

~If it doesn't try running this:~
~1. `npm uninstall tailwindcss`~
~2. `./vendor/bin/wpemerge install` and choose TailwindCSS again~

Actually, run `composer update` - your cli dependency is one patch version behind - it should be `0.11.1`

**Comment by ProxyAi** [comment]
Thank you that did the trick
