### ISSUE TITLE
Is it easy to integrate Angular or React JS frameworks into this theme's development workflow?

### ISSUE THREAD

**Issue by distributev** [htmlburger/wpemerge-theme#21]
Both have CLI versions (angular CLI and create-react-app) and both generate their own folder structure which is different from the folder structure of wpemerge-theme folder structure. Both have their own webpack configurations and development workflow / dev server so how would one properly integrate these into WordPress wpemerge-theme?

**Comment by atanas-dev** [comment]
Hi @distributev ,

The CLIs you mentioned create stand-alone fully-fledged webpack setups so it won't be easy to merge them together with the theme (create-react-app doesn't expose its webpack setup at all unless you eject, for example).

Regardless, you can create a lightweight setup for React, for example, by adding [babel-preset-react](https://www.npmjs.com/package/babel-preset-react) and [react-hot-loader](https://github.com/gaearon/react-hot-loader).
