### ISSUE TITLE
Uncaught WPEmergeTheme\Concerns\JsonFileNotFoundException: The required manifest.json file is missing. Please run one of the build commands to generate it.

### ISSUE THREAD

**Issue by ghost** [htmlburger/wpemerge-theme#22]
## Version

  - WP Emerge Starter Theme: 0.12.0
  - WP Emerge (if not the default):
  - WordPress: 5.1.1
  - PHP: 7.1
  - Operating System: Windows 10 Enterprise (Version 1809)

## Expected behavior

Theme should initialize.

## Actual behavior

Uncaught WPEmergeTheme\Concerns\JsonFileNotFoundException: The required manifest.json file is missing. Please run one of the build commands to generate it.

## Steps to reproduce (in case of a bug)

  1. Browse to wp-content/themes.
  2. Run composer create-project htmlburger/wpemerge-theme wpemerge-me
  3. Active theme in wordpress backend. 

## Comments

Seems the theme is looking for a manifest.json file. The function is called here:
wordpress\wp-content\themes\wpemerge-me\vendor\htmlburger\wpemerge-theme-core\src\Assets\Manifest.php

**Comment by atanas-dev** [comment]
Hi @webicians ,

As the exception states you need to run one of the build commands to generate the required manifest (e.g. `yarn build`). Regardless, this behavior has already been changed and this exception will no longer be thrown in the next release.
