### ISSUE TITLE
Invalid release zip

### ISSUE THREAD

**Issue by nunof07** [htmlburger/wpemerge-theme#25]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge Starter Theme: 0.15.0
  - WP Emerge (if not the default):
  - WordPress: 5.2.2
  - PHP: 7.1.3

I'm running on Windows, if that helps.

## Expected behavior

`yarn release` generates a valid zip archive.

## Actual behavior

`yarn release` generates an invalid zip archive. The zip cannot be opened/extracted.

No errors shown while executing the command.

Tried opening with PeaZip and Windows zip utility.

## Steps to reproduce (in case of a bug)

  1. Install the latest version: `composer create-project htmlburger/wpemerge-theme your-theme-name`.
  1. Change to theme directory: `cd your-theme-name`.
  1. Run install directly (since I'm on Windows). `.\vendor\bin\wpemerge install` (I have to use these slashes).
  1. Generate release zip: `yarn release`.
  1. Try to open the zip file.

## Comments

I think this is probably an issue with the `archiver` package. Seems to have some open issues on Windows but couldn't find an exact one.

**Comment by atanas-dev** [comment]
Fixed in master. Thank you for the report!

**Comment by nunof07** [comment]
Thanks!
