### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method WPEmergeTheme\Theme\Theme::make()

### ISSUE THREAD

**Issue by trompx** [htmlburger/wpemerge-theme#30]
## Version

  - WP Emerge Starter Theme: 0.15.1
  - WordPress: 5.2.2
  - PHP: 7.3.6

## Expected behavior

Method found

## Actual behavior

```
Fatal error: Uncaught Error: Call to undefined method WPEmergeTheme\Theme\Theme::make()
in /usr/src/wordpress/wp-content/themes/project/theme/functions.php:66 Stack trace: #0
/usr/src/wordpress/wp-settings.php(499): include() #1 /usr/src/wordpress/wp-config.php(152):
require_once('/usr/src/wordpr...') #2 /usr/src/wordpress/wp-load.php(37):
require_once('/usr/src/wordpr...') #3 /usr/src/wordpress/wp-blog-header.php(13):
require_once('/usr/src/wordpr...') #4 /usr/src/wordpress/index.php(17):
require('/usr/src/wordpr...') #5 {main} thrown in /usr/src/wordpress/wp-content/themes/project/theme/functions.php on line 66
```

## Steps to reproduce (in case of a bug)

  1. Run composer install
  2. run yarn dev
  3. visit homepage, install wordpress then activate the theme
  

## Comments

I have a particular config but it works fine for other project.
I run all my projects in docker container inside VM.
So I mount the code project (with node modules and vendor) inside docker.
I could install wordpress correctly.

**Comment by atanas-dev** [comment]
Hi @trompx ,
It seems you are using `master` for your theme instead of `0.15.1` - this is not recommended. Always use a release.

**Comment by trompx** [comment]
Hey @atanas-angelov-dev,
Thanks a lot for the fast answer. That totally did it. Sorry I thought master was at the 0.15.1 level.
