### ISSUE TITLE
This documentation package is very difficult!

### ISSUE THREAD

**Issue by webafra** [htmlburger/wpemerge-theme#31]
- WP Emerge Starter Theme
  - WordPress: 5.2.2
  - PHP: 7.2

This documentation package is very difficult!

Unfortunately, the documentation of this package is grossly misleading.
For the easiest thing, you can not use the documentation, for example, the engine does not have the correct guidance for setting up the engine, and in the end I did not succeed.

In the first step, I installed the WP Emerge Blade with Composer.
In the second step, I added the following code in the configuration file (not at all referred to as the file):
\ WPEmergeBlade \ View \ ServiceProvider :: class

What should I do to use it?

**Comment by atanas-dev** [comment]
Hi @webafra ,

What exactly is not working after you added the service provider class to the `'providers'` array in your configuration?
If you get any errors - could you please share them?
If you are using the starter theme don't miss the 3rd step to replace your templates with the ones from the `theme/alternative/blade/` directory.

**Comment by webafra** [comment]
thanks @atanas-angelov-dev 

yes , i used starter theme and move all file and replace files : 
move all file in theme/alternative/blade/ to theme/

![image](https://user-images.githubusercontent.com/8689072/61718609-96d91280-ad78-11e9-801d-84aff8b3e694.png)

Error after move files : 

Fatal error: Uncaught Error: Call to undefined function WPEmerge\render() in /Volumes/FileDrive/projects/wordpress/wp-content/themes/wpemerge-theme/theme/index.php:8 Stack trace: #0 /Volumes/FileDrive/projects/wordpress/wp-includes/template-loader.php(78): include() #1 /Volumes/FileDrive/projects/wordpress/wp-blog-header.php(19): require_once('/Volumes/FileDr...') #2 /Volumes/FileDrive/projects/wordpress/index.php(17): require('/Volumes/FileDr...') #3 /Users/webafra/.composer/vendor/laravel/valet/server.php(151): require('/Volumes/FileDr...') #4 {main} thrown in /Volumes/FileDrive/projects/wordpress/wp-content/themes/wpemerge-theme/theme/index.php on line 8
The site is experiencing technical difficulties


index.php file content : 
```
<?php
/**
 * This file is required by WordPress. Delegates the actual rendering to index.blade.php.
 *
 * @package WPEmergeTheme
 * phpcs:disable
 */
WPEmerge\render( 'index' );
```

**Comment by atanas-dev** [comment]
Hi @webafra 

Unfortunately I was unable to reproduce the issue. I followed the quickstart steps as listed in the docs in order:
1. https://docs.wpemerge.com/#/starter-theme/quickstart
2. https://github.com/htmlburger/wpemerge-blade

Please make sure you follow the steps exactly. Alternatively, this may be an issue with Valet as it is made specifically for Laravel development.
