### ISSUE TITLE
Route handle controller is not called

### ISSUE THREAD

**Issue by trompx** [htmlburger/wpemerge-theme#32]
## Version

  - WP Emerge Starter Theme: 0.15.1
  - WordPress: 5.2.2
  - PHP: 7.3.6

## Expected behavior

Home controller home method should be called

## Actual behavior

The route is not going through the home controller

## Comments

I added in src/Controllers/Web/HomeController.php
```
<?php
namespace App\Controllers; // with and without
class HomeController {
  public function index( $request, $view ) {
      return WPEmerge\view( 'templates/home' );
  }
}
```

In routes/web.php, the following is not working
`Route::get()->url( '/' )->handle( 'HomeController@index' );`

while the following return the expected template
```
Route::get()->url( '/' )->handle( function() {
  return WPEmerge\view( 'templates/home' );
} );
```

May I suggest you add to the starter theme basic usage like first route + first controller so it is easier for people to start / replace.

**Comment by trompx** [comment]
The following correct the issue:
`namespace App\Controllers\Web;`

But creates another issue:
`Call to undefined function App\Controllers\Web\WPEmerge\view()`

**Comment by trompx** [comment]
Using finally works:
`return \WPEmerge\view( 'templates/home' );`

I think adding this simple controller + simple view + simple route in the starter theme or at least having the proper doc would help others.

The doc here https://docs.wpemerge.com/#/framework/0-to-100-setup is confusing as it does not take into account the new folder structure (Controllers/Web-Admin...)

**Comment by atanas-dev** [comment]
You are correct - the docs are slightly outdated and missing the new directory structure. I will be updating them shortly.

**Comment by atanas-dev** [comment]
Docs are updated (cache may apply) - let me know if you stumble upon any other inaccuracies:
https://docs.wpemerge.com/#/framework/0-to-100-setup
