### ISSUE TITLE
admin create new route not work

### ISSUE THREAD

**Issue by webafra** [htmlburger/wpemerge-theme#34]
i added this route on admin.php 
```
Route::get()->where( 'admin', 'my-custom-admin-page-slug' )->handle( 'ExampleController@admin' );
```

how to access this route ? 
http://wordpress.test/wp-admin/my-custom-admin-page-slug   ?

**Comment by atanas-dev** [comment]
This condition matches against pages registered with [add_menu_page()](https://developer.wordpress.org/reference/functions/add_menu_page/) or [add_submenu_page()](https://developer.wordpress.org/reference/functions/add_submenu_page/) as stated in the docs:
https://docs.wpemerge.com/#/framework/routing/conditions?id=admin

The URL depends on which one you use and the parent slug in the case of `add_submenu_page()`. Refer to the WordPress docs on each function for the exact URL.

**Comment by webafra** [comment]
It would be better if you wrote a sample for each section.
