### ISSUE TITLE
500 on Apache instances due to duplicate headers

### ISSUE THREAD

**Issue by tsudarshan** [htmlburger/wpemerge-theme#35]
## Version 0.15.0
  - WordPress: 5.2.2
  - PHP: 7.3

## Expected behavior
Frontend/ Backend to load with the starter theme

## Actual behavior
500 Internal Server Error

## Comments

On Apache (MAMP etc) stacks, the theme throws a 500 instantly with all dependencies met & installed.

Upon closer inspection, it wasn't a PHP exception but an Apache exception due to duplicate headers being sent. It appears both `ResponseService` class from `wpemerge` and `BladeView` extensible class on `wpemerge-blade` are sending 'Content-type' headers which is throwing the exception. In the team I work with, nginx isn't complaining after all.

Line references to the conflicting headers being output (on the starter theme with all dependencies including wpemerge core and wpemerge-blade installed):
- `/vendor/htmlburger/wpemerge/src/Responses/ResponseService.php` L51 -> `respond` function
- `/vendor/htmlburger/wpemerge-blade/src/View/BladeView.php` L56 -> `toResponse` function

The `respond` function on wpemerge core seems to be outputting conditionally (`if ( ! headers_sent() )`), however, the issue persists.

Commenting out either/ or one of the output resolves the issue. I'm wary of commenting out the headers from being sent as part of the response object on the wpemerge-core as that'll probably strip other headers too. For now, I'm sticking with commenting out the single header addition on `BladeView` class.

Any thoughts?

TIA,
Sudarshan

**Comment by atanas-dev** [comment]
Hi @tsudarshan ,

Could you please add the exact error from the Apache logs as well? Thanks.

**Comment by tsudarshan** [comment]
Sure @atanas-angelov-dev 

```
[Wed Aug 21 13:51:59 2019] [error] [client ::1] FastCGI: comm with server "/Applications/MAMP/fcgi-bin/php7.3.fcgi" aborted: error parsing headers: duplicate header 'Content-type', referer: http://[obfuscated].local/wp-admin/tools.php?page=wp-sync-db
```

Happens on any page that is hit. This one ^ is taken just a few seconds ago after uncommenting the `toResponse` function on BladeView class again to obtain the error message when I was on WPMigrateDB backend.

_Note: I've obfuscated my local domain for integrity_

Thank you for taking the time to look into this.

**Comment by atanas-dev** [comment]
The issue has been fixed in master and will make it into the next release.

**Comment by tsudarshan** [comment]
Thanks a lot, Atanas.
