### ISSUE TITLE
Unable to activate

### ISSUE THREAD

**Issue by rastitkac** [htmlburger/wpemerge-theme#36]
## 0.15.1

  - WP Emerge Starter Theme: 0.15.1
  - WP Emerge (if not the default): default
  - WordPress: 5.2.2
  - PHP: 7.2

## Expected behavior

Being able to actually activate the theme in wordpress.

## Actual behavior

After following quick start instructions can't activate the theme in wp-admin nor wp-cli.

## Comments

What am I missing?

**Comment by atanas-dev** [comment]
Hi @rastitkac ,

Could you please clarify what you mean exactly by "can't activate" - is it missing from the list of themes, do you get an error (if yes - what is it?), do you activate it but it your current theme remains the active one instead etc.

**Comment by rastitkac** [comment]
Hi @atanas-angelov-dev 

Sorry for not being clear and sorry for late replay (I missed the notification).
After installing the theme by running `composer create-project htmlburger/wpemerge-theme test` the files in the resulting folder `test` didn't resemble a WordPress theme (see attached screenshot).
When I tried to activate it `wp theme activate test`, I got "Stylesheet is missing" error.
<img width="544" alt="Screenshot 2019-09-04 at 22 27 37" src="https://user-images.githubusercontent.com/23151096/64289240-30910380-cf64-11e9-879a-11c0249fb03a.png"> and couldn't see it in wp-admin/themes.php

Later I found out, I could activate by `wp theme activate test/theme`.
But I still haven't found out why I can't see it in admin.

**Comment by atanas-dev** [comment]
Thanks for the extra info @rastitkac !

The structure you are seeing is as expected - the theme currently ~abuses~ takes advantage of nested theme directory support to organize files a little differently. While it can lead to activation quirks like this, the theme should be visible in the administration panel - are you using an atypical environment like Bedrock or similar, for example?

Just a heads up, the special directory structure is getting a revamp in the next release so this will no longer be an issue when it goes live (it's still some time away though).
