### ISSUE TITLE
Intergration with WooCommerce

### ISSUE THREAD

**Issue by patrikarvidsson** [htmlburger/wpemerge-theme#38]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge Starter Theme: Not sure, CLI shows 0.15.0.
  - WP Emerge (if not the default):
  - WordPress: 5.2.3
  - PHP: 7.3

## Expected behavior

WooCommerce using template files from WPEmerge.

## Actual behavior

WooCommerce seems to not use template files from WPEmerge. 

WPEmerge works great for Wordpress, and I might be missing something now, but as soon as you get to a WooCommerce page it seems to ignore the standard template files (using Blade, but standard ones does the same). 

This results in different header, footer, nav and general site structure. It would be nice if WooCommerce is rendered within the existing WPEmerge site structure from the template files.

Have I missed anything to make it work?

## Comments

I'm in the process of migrating a client website over from Sage, and is well underway but ran into above problems with WooCommerce. Big thumbs up on this project, it's really a breeze to work with.

**Comment by atanas-dev** [comment]
Hi @patrikarvidsson ,

Do you know which files exactly is Woo loading instead of your theme's? For example, you have your theme's header.blade.php/header.php but instead of that one which one does Woo load?

**Comment by patrikarvidsson** [comment]
Not exactly, sorry, but I can give you access to the codebase if it helps. 

The menu is missing and the header is only the site name. Also the layout markup is different. The body class, however, is indicating it is the correct theme that is loaded.

**Comment by atanas-dev** [comment]
@patrikarvidsson if you feel comfortable you can give me read-only access to the repo or email me whatever access/copies you wish at hi@atanas.dev.

**Comment by patrikarvidsson** [comment]
Seems I can't give you read access for private repositories. I checked what header was read in with the help of a plugin, and it shows this:

`themes/nameOfTheme/theme/header.php`

This row doesn't appear on the start page, for example. I recall there was another issue about something similar, #24, supposedly solving it in an upcoming release. I don't know if it has anything to do with this issue, but I'll take a look at it again.

Further, the **template** used on `/shop/` is `themes/nameOfTheme/theme/index.blade.php`.

Sent you a mail anyway, with a few extra details. Worth mentioning is I also tried patching to 0.15.1, but no patch was applied, so maybe I'm already using 0.15.1 even though cli shows 0.15.0.

**EDIT**: Start page was using `front-page.blade.php` by the way, and temporarily renaming that files makes it use `index.blade.php` instead. Still no `header.php` usage on the front page though.

**Comment by atanas-dev** [comment]
Resolved in a private discussion.

**Comment by sybbear** [comment]
@atanas-angelov-dev Would resolution be available in the next version?

**Comment by atanas-dev** [comment]
@vikingmaster the issue was a local one, not specific to WP Emerge so there is nothing to fix.

EDIT:
There will be some improvements to WooCommerce support in the near future as a result though.

**Comment by sybbear** [comment]
@atanas-angelov-dev Gotcha, thank you!
