### ISSUE TITLE
Script WPEmerge\Cli\App::createConfigJson handling the post-create-project-cmd event terminated with an exception

### ISSUE THREAD

**Issue by zamanq** [htmlburger/wpemerge-theme#42]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge Starter Theme: 0.15.1
  - WP Emerge (if not the default):
  - WordPress: 5.3.2
  - PHP: 7.3.5

## Expected behavior
I expected to see the theme install correctly. 
_Please describe the expected behavior here._
I expected a complete flawless install with proper configuration and additional options to add my preferred css frameworks
## Actual behavior
Instead I got this error "Script WPEmerge\Cli\App::createConfigJson handling the post-create-project-cmd event terminated with an exception"
_Please describe the actual, unexpected behavior here._
ERROR: Script WPEmerge\Cli\App::createConfigJson handling the post-create-project-cmd event terminated with an exception

 [ErrorException]
  Trying to access array offset on value of type int

## Steps to reproduce (in case of a bug)

  1.
  1.
  1.

## Comments
I'm on MacOS Catalina 10.15.2 if that helps.
_Please add any other comments here._

**Comment by atanas-dev** [comment]
The issue has been fixed in master - for more information and a work-around please refer to https://github.com/htmlburger/wpemerge-theme/issues/43#issuecomment-617930863.
