### ISSUE TITLE
CSS edit triggers full page reload

### ISSUE THREAD

**Issue by EstebanForge** [htmlburger/wpemerge-theme#44]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge Starter Theme: 0.15.1
  - WordPress: 5.3.2
  - PHP: 7.3

## Expected behavior

By the info shown at /resources/build/browsersync.js (injectCss = true) i think the theme should hot-reload and inject the css without a full page reload.

## Actual behavior

Changing some SCSS will trigger a full page reload.

## Steps to reproduce (in case of a bug)

  1. Install a fresh wpemerge-theme, use scss.
  2. yarn dev
  3. change something in /resources/styles/theme/index.scss and watch a full page reload to happen.

## Comments

Video: https://photos.app.goo.gl/mszfYYFiffmzbsmM8
yarn dev at 40 seconds mark.

**Comment by atanas-dev** [comment]
Hi @TCattd ,

The BrowserSync Webpack plugin only ever injected CSS when no non-css files were output by webpack during a change which was never the case in the theme.
I've replaced BrowserSync with Webpack Dev Server in `master` which resolves the issue and includes some other goodies (e.g. an error overlay when compilation fails).
