### ISSUE TITLE
Unable  to contribute

### ISSUE THREAD

**Issue by paulomfr** [htmlburger/wpemerge-theme#45]
## Version

  - WP Emerge Starter Theme: 0.15.1
  - WordPress: 5.4
  - PHP: 7.4.2

## Expected behavior
Activate theme to  contribute.

## Actual behavior
When run `composer install` and then try to activate the theme, is returned and error saying that `App::make()` is an undefined method.

## Steps to reproduce (in case of a bug)

  1. Clone this repo.
  2. Run `composer install && composer run post-create-project-cmd` .
  3. Activate the WP Emerge theme from your WordPress admin panel.

## Comments

**Screenshots:**

_Screen_
<img width="775" alt="Screen Shot 2020-04-12 at 11 55 27" src="https://user-images.githubusercontent.com/13263721/79071924-a573ab00-7cb4-11ea-888b-eaf7bb3fbd37.png">

_/app/src/App.php_
![The app](https://user-images.githubusercontent.com/13263721/79071965-e1a70b80-7cb4-11ea-81b1-4ac78774a64e.png)

**Comment by atanas-dev** [comment]
Hi @paulomfr ,

The CONTRIBUTING.md docs are incorrect - you need the master version of the framework in order for the master version of the theme to work (at least right now). This should resolve the issue:
`composer require htmlburger/wpemerge:dev-master`

**Comment by paulomfr** [comment]
Hi @atanas-dev,

I got this error.

<img width="1404" alt="Screen Shot 2020-04-12 at 13 09 29" src="https://user-images.githubusercontent.com/13263721/79073806-f1c3e880-7cbe-11ea-8ec3-bac7b66be3c9.png">

**Comment by atanas-dev** [comment]
Try changing the required versions in composer.json of these dependencies to `dev-master`:
- `htmlburger/wpemerge`
- `htmlburger/wpemerge-theme-core`
- `htmlburger/wpemerge-cli`

`master` is quite volatile right now so it's a bit rough to set up.

**Comment by paulomfr** [comment]
I've changed the required versions and got this error...

<img width="577" alt="1-1" src="https://user-images.githubusercontent.com/13263721/79074592-ae1fad80-7cc3-11ea-8469-be2a5fa5af45.png">

<img width="1498" alt="1" src="https://user-images.githubusercontent.com/13263721/79074590-ac55ea00-7cc3-11ea-92c3-44318c48a761.png">

Then I've changed the `htmlburger/wpemerge` to `~0.15.0`, and got this error:

<img width="768" alt="Screen Shot 2020-04-12 at 13 45 22" src="https://user-images.githubusercontent.com/13263721/79074628-dd361f00-7cc3-11ea-90e7-a168a46efd49.png">

**Comment by atanas-dev** [comment]
Please revert the changes I mentioned and update your composer.json to this:
```json
{
  "name": "htmlburger/wpemerge-theme",
  "version": "0.15.1",
  "description": "A modern WordPress starter theme which uses the WP Emerge framework",
  "type": "wordpress-theme",
  "keywords": ["wordpress", "theme", "starter theme", "wpemerge"],
  "license": "GPL-2.0-only",
  "homepage": "https://wpemerge.com/",
  "authors": [
    {
      "name": "Atanas Angelov",
      "email": "atanas.angelov.dev@gmail.com",
      "homepage": "https://github.com/atanas-angelov-dev/",
      "role": "Developer"
    },
    {
      "name": "htmlBurger",
      "email": "info@htmlburger.com",
      "homepage": "http://htmlburger.com/",
      "role": "Developer"
    }
  ],
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/htmlburger/wpemerge.git"
    },
    {
      "type": "git",
      "url": "https://github.com/htmlburger/wpemerge-theme-core.git"
    },
    {
      "type": "git",
      "url": "https://github.com/htmlburger/wpemerge-cli.git"
    }
  ],
  "require": {
    "php": ">=5.5",
    "composer/installers": "^1.4",
    "htmlburger/wpemerge": "dev-master as 0.15.1",
    "htmlburger/wpemerge-theme-core": "dev-master as 0.15.1",
    "htmlburger/carbon-pagination": "^1.1.6"
  },
  "require-dev": {
    "filp/whoops": "^2.2",
    "htmlburger/wpemerge-cli": "dev-master as 0.15.1",
    "symfony/debug": "~3.0",
    "wp-coding-standards/wpcs": "^2.0",
    "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0"
  },
  "autoload": {
    "psr-4": {
      "App\\": "app/src/"
    }
  },
  "scripts": {
    "install-test-env":[
      "WPEmerge\\Cli\\App::createConfigJson"
    ],
    "post-create-project-cmd": [
      "WPEmerge\\Cli\\App::createConfigJson",
      "WPEmerge\\Cli\\App::installDependencies",
      "WPEmerge\\Cli\\App::buildAssets",
      "WPEmerge\\Cli\\App::install"
    ]
  }
}
```
(the changes are in the `repositories`, `require` and `require-dev` keys where we "lie" to composer about what version should be loaded for the dependencies)

If you have forked any of the other packages, please replace the respective url in `repositories` above.

Then remove your composer.lock file and run `composer install`.

**Comment by paulomfr** [comment]
Now worked! Thank you!

**Comment by atanas-dev** [comment]
The CONTRIBUTING.md docs have been brought up to date 👍
