### ISSUE TITLE
Add support for Gutenbeg Editor Styles

### ISSUE THREAD

**Issue by yumyo** [htmlburger/wpemerge-theme#47]
## Expected behaviour

Editor styles are correcting recognised, transformed and inlined by Gutenberg.

## Actual behaviour

Editor styles are not recognised so the default styles are inlined instead. 
This cause having to rely on unnecessary CSS !important rules or additional selectors. 

## Comments

Solved by commenting out the current editor.css enqueue in `app/helpers/assets.php` in favour of adding:

```
/**
 * Support the theme’s editor styles.
 *
 * @link https://developer.wordpress.org/block-editor/developers/themes/theme-support/#editor-styles
 */

add_theme_support( 'editor-styles' );
add_editor_style(  '../dist/styles/editor.css');
```
to `app/setup/theme-support.php`

**Comment by atanas-dev** [comment]
Thank you for the report @yumyo - the issue has been fixed in master.
