### ISSUE TITLE
Wrong PHPDocBlock

### ISSUE THREAD

**Issue by elvishp2006** [htmlburger/wpemerge-theme#48]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge Starter Theme: 0.16.0

## Actual behavior

[* @return array|void](https://github.com/htmlburger/wpemerge-theme/blob/483a4d601f04ea8eff3048a418d6480ef125a42a/app/version.php#L16)

**Comment by atanas-dev** [comment]
Thank you for the report - it's now fixed in master.
