### ISSUE TITLE
Timeout on install css package

### ISSUE THREAD

**Issue by paulomfr** [htmlburger/wpemerge-theme#5]
## Version
0.9.1

When I try to install some of css package, I have a timeout error:

![wpemerge-timeout](https://user-images.githubusercontent.com/13263721/41738792-6bb38966-7569-11e8-9915-b212f3d633fa.png)

**Comment by atanas-dev** [comment]
It seems yarn takes too long - I'll probably have to increase the timeout.
To fix this just run `yarn remove tachyons` and run `./vendor/bin/wpemerge install` again and go through the process. Yarn will have the package cached now so it should be much faster.

**Comment by atanas-dev** [comment]
Fixed in htmlburger/wpemerge-cli@11493acf29d15ecd2d9b7fd2e25b89e9484bebb7

**Comment by jleei** [comment]
still timeout, tried many times. please consider to increase 120s to 600. 

![2018-12-20 15 03 01](https://user-images.githubusercontent.com/1852808/50269430-304de800-0469-11e9-84c2-0db851e31bb1.png)

**Comment by atanas-dev** [comment]
Fixed in htmlburger/wpemerge-cli@55e26b6aa004dd19af635e02355aac31fa1841d5
