### ISSUE TITLE
Unable to load SVG files as image.

### ISSUE THREAD

**Issue by paulomfr** [htmlburger/wpemerge-theme#59]
## Version
  - WP Emerge Starter Theme: 0.16.1

## Expected behavior
Be able to use a SVG file as image in the project.

## Actual behavior
When adding a SVG inside `images` folder, the `font-loader` is creating the file inside `fonts` folder and adding a `export` statement in the SVG file.

## Comments

![svg-file-loaded-in-images-folder-with-export-statement](https://user-images.githubusercontent.com/13263721/83873145-9b48b880-a709-11ea-9d54-d26805fe4716.jpeg)

**Comment by atanas-dev** [comment]
Fixed in 94935d7446b456048b24c3f16cc397044a3d99be.
If you feel comfortable applying patches manually, you can use this:
https://github.com/htmlburger/wpemerge-theme/commit/94935d7446b456048b24c3f16cc397044a3d99be.patch
