### ISSUE TITLE
Feature request: image asset processing & subfolders

### ISSUE THREAD

**Issue by codemonkeynorth** [htmlburger/wpemerge-theme#61]
## Version

  - WP Emerge Starter Theme: 0.16.1
  - WP Emerge (if not the default): master (0.16.1)

## Expected behavior

* It would be useful to be able to process images that aren't directly referenced/findable in css/js etc and so get missed out of `dist`

* images in subdirectories eg `resources/images/icons` should be output with the same path structure

## Steps to reproduce (in case of a bug)

  1. add an image to /resources/images/icons/icon.png
  2. build

=> observe image is not output to `/dist/images/icons/icon_{manifest_id}.png`

## Comments

**re: image paths**.. the following code is a potential fix...
```
name: (f) => {
    const dirNameInsideResources = path.relative('resources', path.dirname(f));
    return `${dirNameInsideResources}/[name].${utils.filehash(f).substr(0, 10)}.[ext]`;
},
```

**re: image references & compiling as asset**

Currently I create a `scripts/assets/index.js` file to reference any images that aren't used in  css or js directly so it picks them up and outputs them to `dist\images` accordingly. 

(It creates a dummy `assets.min.js` file which doesnt need to be used by anything on the site. It's not perfect but is a way to ensure images are picked up and output to `dist`)

eg if I `import '@images/test/test-emblem.png';` in my `assets/index.js` then this is output to the dist folder
`/images/test/test-emblem.44a9352841.png`

I then have an `asset` helper function

`<img src="{{ asset('images/test/test-emblem.png') }}" />`

```
function asset($file) {
    $asset = \App::core()->assets()->getAssetUrl($file);
    return $asset;
}
```

hopefully some of this could maybe incorporated by default?

thanks
J

**Comment by atanas-dev** [comment]
Images and fonts will now keep their directory structure relative to `resources/images/` and `resources/fonts/` respecitvely. Images and fonts imported from other directories (e.g. node_modules) will now be inserted into a new `vendor` directory:
| Src | Dist |
| --- | --- |
| resources/images/foo.png | dist/images/foo.{HASH}.png |
| resources/images/subdir/foo.png | dist/images/subdir/foo.{HASH}.png |
| node_modules/some-package/foo.png | dist/images/vendor/foo.{HASH}.png |

These changes are now in master and will make it into the next release.
