### ISSUE TITLE
Problems using the yarn:hot script

### ISSUE THREAD

**Issue by smachi** [htmlburger/wpemerge-theme#62]
## Version

  - WP Emerge Starter Theme: 0.16.1
  - WP Emerge (if not the default): 0.16.0
  - WordPress: 5.5
  - PHP: 7.3.9

## Issue

 I'm using MAMP for development and the dev URL is a local domain (like mydomain.loc). I've set the domain in config.json (as url and hotUrl).

- If I set the port in config.json to any number distinct of 80, it shows a page with some kind of file browser where all the theme files are listed
- If I set the post to 80, it shows an error: "Error: listen EACCES: permission denied 127.0.0.1:80"

I've also tried to leave the default localhost URL in the config.json and the result is the same (a file listing page).

What am I doing wrong?

**Comment by smachi** [comment]
Never mind. I just figured it out.
Just changed the port to 3000 and it's working on the custom domain now :)

**Comment by atanas-dev** [comment]
Happy to hear you resolved the problem!

For clarification, the port by default is 3000 so you don't need to adjust it.
Also, you're not supposed to actually open `mydomain.loc:3000` in your browser - this port is set up for Webpack to communicate changes and refresh the page.

To summarize, regardless of whatever the port in config.json is you should open `mydomain.loc` in your browser without the port (unless your webserver demands it of course).

**Comment by smachi** [comment]
Yes, I've understood that when it started working. Thanks @atanas-dev
