### ISSUE TITLE
Unknown file wpcs.xml in package.json

### ISSUE THREAD

**Issue by yanmorinokamca** [htmlburger/wpemerge-theme#64]
## Version
master (2020-10-07)
https://github.com/htmlburger/wpemerge-theme/blob/master/package.json

## Expected behavior

"yarn lint-fix" should work

## Actual behavior

File wpcs.xml is not found

## Steps to reproduce (in case of a bug)

  1. yarn lint-fix

## Comments

I guess it should use --standard=phpcs.xml  link lint:wpcs command ?

**Comment by atanas-dev** [comment]
Thank you for the report @yanmorinokamca!
Your assumption is correct - the wpcs:lint-fix command has an outdated reference to wpcs.xml which should be phpcs.xml instead.

I've fixed the issue in https://github.com/htmlburger/wpemerge-theme/commit/bc0e6b1984d53dd815f64b993bbf0d31ffb7d78f and https://github.com/htmlburger/wpemerge-plugin/commit/4d63650e1b6b69a3bb4725e6e8ef48c5dc9387b3
