### ISSUE TITLE
Make Compatible with Composer 2

### ISSUE THREAD

**Issue by justlevine** [htmlburger/wpemerge-theme#65]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge Starter Theme: 0.16.1
  - WP Emerge (if not the default):
  - WordPress: 5.5
  - PHP: 7.4

## Expected behavior

Installing the theme with Composer v2 should work.
## Actual behavior
```
  Problem 1
    - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.5.0 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0].
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```
## Steps to reproduce (in case of a bug)

  1. Run `composer create-project htmlburger/wpemerge-theme wpemerge`.
2. View error.

## Comments
Seemingly, updating `composer.json > dealerdirect/phpcodesniffer-composer-installer` to "^0.7" seems to fix it, but im not sure of the side-effects.

**Comment by atanas-dev** [comment]
Thank you for the report @justlevine!
This is now fixed in 594c2766cf8f9de03f9bedd0e1dd5bfced9a9364. Until this ships you can apply the fix from the commit manually to your `composer.json` to get it to work with Composer 2 - from what I could find/test there were no side effects of using ^0.7.
