### ISSUE TITLE
Update to TailwindCSS 2 ?

### ISSUE THREAD

**Issue by cthom-dev** [htmlburger/wpemerge-theme#67]
Hi,

Firstly thanks for making such a great framework and theme. I'm from a Laravel background so I really want to try this, plus your documentation is top notch. I appreciate the info for Bedrock users.

When do you think you will have TailwindCSS 2 implemented?

**Comment by atanas-dev** [comment]
Fixed in htmlburger/wpemerge-theme@dff69e21e2a4a2b1cd1a30a1630498e87fb8223d and htmlburger/wpemerge-cli@56d319282625e47b4c59da5bd6bb5718f0afcccf so keep an eye out for the next release which will include those.
