### ISSUE TITLE
"failed to open stream" Error

### ISSUE THREAD

**Issue by kristjankoppel** [htmlburger/wpemerge-theme#9]
## Version
  - WP Emerge Starter Theme: latest
  - WordPress: 4.9.8
  - PHP: 7.1

## Actual behavior

While installing CSS framework i get error like this:
`Warning: file_get_contents(/Users/kristjankoppel/Propxls/clients/flowit/cms/wp-content/themes/flowit/resources/css/_vendor.css): failed to open stream: No such file or directory in /Users/kristjankoppel/Propxls/clients/flowit/cms/wp-content/themes/flowit/vendor/htmlburger/wpemerge-cli/src/Presets/StatementAppenderTrait.php on line 17`
`Warning: file_put_contents(/Users/kristjankoppel/Propxls/clients/flowit/cms/wp-content/themes/flowit/resources/css/_vendor.css): failed to open stream: No such file or directory in /Users/kristjankoppel/Propxls/clients/flowit/cms/wp-content/themes/flowit/vendor/htmlburger/wpemerge-cli/src/Presets/StatementAppenderTrait.php on line 33`

## Steps to reproduce (in case of a bug)

- follow Quickstart guide

## Comments
I wanted to try wpemerge-theme and setup my local WP setup. Then i followed the Quickstart guide found here: https://docs.theme.wpemerge.com/quickstart.html 
I chose my options and first time installing i got error: 
`The process "yarn add "bootstrap@^3.3" --dev" exceeded the timeout of 60 seconds.`
Then i removed the whole theme folder and started again. After that i didn't get timeout error only that failed to open stream error. Also i'm using Lando(https://docs.devwithlando.io) for my local development environment.

**Comment by atanas-dev** [comment]
Hi @kristjankoppel ,

Both issues have already been fixed, however, packagist.org is refusing to update one of the packages which kind of ties my hands.
I'll update this issue once the packagist.org issue is solved.

Here's a short step-by-step guide on how to add Bootstrap manually in the meantime:
1. Execute `yarn add --dev bootstrap@^4.0` in the theme root directory.
2. Edit `resources/styles/_vendor.scss` and add this line at the end:
    ```
    @import '~bootstrap/dist/css/bootstrap.css';
    ```
That should be it!

**Comment by kristjankoppel** [comment]
OK. I think i got everything now working. Did a quick test with few Booststrap components. Too bad i need to do these steps manually.

So here is few steps if anyone want to get this theme running with **Bootstrap 4.1.3**.

1. cd into your freshly created theme folder
2. run `yarn add bootstrap@4.1.3 --dev`
3. run `yarn add popper.js --dev`
4. For CSS edit  `resources/styles/_vendor.scss` and add this line at the end: 
`@import '~bootstrap/scss/bootstrap.scss';`
Note that you can even import BS partial parts. Same for bootstrap javascript.
5. For JS edit `resources/scripts/index.js` and add this line at the end: 
`import 'bootstrap';`
6. Now run `yarn dev` or `yarn dev --dev-url=<your-project-ul>` -- everything should work nicely.

Note 1: @atanas-angelov-dev can comment if all this is correct.
Note 2: @atanas-angelov-dev I still want to note that in package.js file there is bootstrap version 3 included: https://jmp.sh/ZaevPeq

**Comment by atanas-dev** [comment]
@kristjankoppel all steps are correct. The version 3 you see is most probably due to the outdated cli tool issue I mentioned.

**Comment by atanas-dev** [comment]
Packagist issue has been fixed (I've missed a special step that the cli tool requires when publishing new versions) and the latest theme and cli tool versions (with the relevant fixes) are now live.

Just as an FYI, the Bootstrap install preset does not add bootstrap and popper's JS to your index.js but I've added that to my TODO so it should be ready for the next version.
